name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

env:
  ARTIFACT: payloadcms.tar.gz

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CD

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} -t ed25519 ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Download production artifact
        uses: actions/download-artifact@v4
        with:
          name: payloadcms

      - name: Deploy artifact
        run: |
          scp -P ${{ secrets.DEPLOY_PORT }} $ARTIFACT ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:$DEPLOY_PATH

      - name: Install & restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          key_path: ~/.ssh/id_ed25519
          envs: DEPLOY_PATH,ARTIFACT
          script: |
            cd $DEPLOY_PATH
            tar xzfv $ARTIFACT
            pnpm i --prod --frozen-lockfile
            pm2 restart
            rm $ARTIFACT
