name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

env:
  ARTIFACT: payloadcms.tar.gz

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CD
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies & build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Archive production artifacts
        run: |
          tar czfv payloadcms.tar.gz dist build package.json pnpm-lock.yaml ecosystem.config.js

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} -t ed25519 ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy artifact
        run: |
          scp -P ${{ secrets.DEPLOY_PORT }} $ARTIFACT ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:$DEPLOY_PATH

      - name: Install & restart service via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          envs: DEPLOY_PATH,ARTIFACT
          script: |
            cd $DEPLOY_PATH
            tar xzfv $ARTIFACT
            pnpm i --prod --frozen-lockfile
            pm2 restart
            rm $ARTIFACT
